### ISSUE TITLE
Can I wrap NemeStats authentication?

### ISSUE THREAD

**Issue by Serneum** [ElixirCLE/nemestats_client#1]
- Send credentials to NemeStats and retrieve the Session token
- Store the session token
- Use session token in future requests

**Comment by joelbyler** [comment]
Looks like you can sign in to nemestats thru their api, [reference this](http://docs.nemestatsapiversion2.apiary.io/#reference/authentication/user-session/create-a-new-user-session)
Requires username and password, returns auth token and expiry date/time

**Comment by Serneum** [comment]
Note: there is currently [an error](https://github.com/NemeStats/NemeStats/issues/503) in the API when trying to use an existing auth token.

**Comment by joelbyler** [comment]
Does this also work for Google Auth? Because apparently that's what I used when I signed up for my NemeStats account

**Comment by Serneum** [comment]
That's a good question. I haven't tried it, but you can try running the `NemeStatsClient.login` function with your Google user/pass
